# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{configurable_engine}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Campbell"]
  s.date = %q{2011-01-10}
  s.description = %q{Configurable allows you to set up config variables in a config file, specifying default values for all environments. These variables can then be set on a per-app basis using a user facing configuration screen. }
  s.email = %q{paul@rslw.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/application_controller.rb",
    "app/controllers/admin/configurables_controller.rb",
    "app/models/configurable.rb",
    "app/views/admin/configurables/show.html.erb",
    "config/routes.rb",
    "dummy/.gitignore",
    "dummy/.rspec",
    "dummy/Gemfile",
    "dummy/Gemfile.lock",
    "dummy/README",
    "dummy/Rakefile",
    "dummy/app/controllers/application_controller.rb",
    "dummy/app/helpers/application_helper.rb",
    "dummy/app/views/layouts/application.html.erb",
    "dummy/config.ru",
    "dummy/config/application.rb",
    "dummy/config/boot.rb",
    "dummy/config/configurable.yml",
    "dummy/config/cucumber.yml",
    "dummy/config/database.yml",
    "dummy/config/environment.rb",
    "dummy/config/environments/development.rb",
    "dummy/config/environments/production.rb",
    "dummy/config/environments/test.rb",
    "dummy/config/initializers/backtrace_silencers.rb",
    "dummy/config/initializers/inflections.rb",
    "dummy/config/initializers/mime_types.rb",
    "dummy/config/initializers/secret_token.rb",
    "dummy/config/initializers/session_store.rb",
    "dummy/config/locales/en.yml",
    "dummy/config/routes.rb",
    "dummy/db/migrate/20110110001344_create_configurables.rb",
    "dummy/db/schema.rb",
    "dummy/db/seeds.rb",
    "dummy/features/admin_configurables.feature",
    "dummy/features/step_definitions/web_steps.rb",
    "dummy/features/support/env.rb",
    "dummy/features/support/paths.rb",
    "dummy/lib/tasks/.gitkeep",
    "dummy/lib/tasks/cucumber.rake",
    "dummy/public/404.html",
    "dummy/public/422.html",
    "dummy/public/500.html",
    "dummy/public/favicon.ico",
    "dummy/public/images/rails.png",
    "dummy/public/index.html",
    "dummy/public/javascripts/application.js",
    "dummy/public/javascripts/controls.js",
    "dummy/public/javascripts/dragdrop.js",
    "dummy/public/javascripts/effects.js",
    "dummy/public/javascripts/prototype.js",
    "dummy/public/javascripts/rails.js",
    "dummy/public/robots.txt",
    "dummy/public/stylesheets/.gitkeep",
    "dummy/script/cucumber",
    "dummy/script/rails",
    "dummy/spec/models/configurable_spec.rb",
    "dummy/spec/spec_helper.rb",
    "dummy/test/performance/browsing_test.rb",
    "dummy/test/test_helper.rb",
    "dummy/vendor/plugins/.gitkeep",
    "lib/configurable_engine.rb"
  ]
  s.homepage = %q{http://github.com/paulca/configurable_engine}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Database-backed configuration for Rails 3, with defaults from config file.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
  end
end

