source 'http://rubygems.org'

gem 'rails', '3.0.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'


gem 'configurable_engine', :path => '../'

group :test do
  gem 'capybara', '0.3.9'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'factory_girl'
  gem "fakeweb"
  gem 'launchy'
  gem "rspec"
  gem "rspec-rails"
  gem 'ruby-debug19'
end
